---
params:
  docTitle: ""
  docDate: ""
  addSpec: ""
  rawData: "" 
  unit: ""
  stdCalib: ""
  invCalib: ""
  weight: ""
  confb2: ""
  order: ""
  equation: FALSE
  concentration: "" 
  confLev: ""
  stdUnc: ""
  expUnc: ""
  confLim: FALSE 
  conLow: ""
  conUpp: ""
  ucrm: ""
  ub0: ""
  uc: ""
  stdPlot: ""
  evalStd: ""
  invPlot: ""
  evalInv: FALSE
  b2: ""
  b1: ""
  b0: ""

output: 
  html_document: default
  pdf_document: default
  word_document: default
---

```{r, include=FALSE}
pretty_print_eq <- function(order, b0, b1, b2) {
    # Create formatted string for each term
    term_b2 <-
      if (b2 == 0)
        ""
    else if (b2 == 1)
      "x^2"
    else if (b2 == -1)
      "-x^2"
    else
      paste0(b2, "x^2")
    term_b1 <-
      if (b1 == 0)
        ""
    else if (b1 == 1)
      "x"
    else if (b1 == -1)
      "-x"
    else
      paste0(b1, "x")
    term_b0 <- if (b0 == 0)
      ""
    else
      as.character(b0)
    
    # Combine terms, handling signs
    if (order == 1) {
      terms <- c(term_b1, term_b0)
    } else{
      terms <- c(term_b2, term_b1, term_b0)
    }
    
    result <- "y ="
    
    for (term in terms) {
      if (term != "") {
        if (substr(term, 1, 1) != "-" && nchar(result) > 3) {
          result <- paste(result, "+", term)
        } else {
          result <- paste(result, term)
        }
      }
    }
    
    # If all coefficients are 0
    if (result == "y =")
      result <- "y = 0"
    
    return(result)
    
  }
```


# **`r params$docTitle`**

**Date generated:** `r params$docDate`

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	warning = FALSE,
	results = "asis"
)
```

```{r}
if(params$addSpec != ""){
cat((paste("**Additional specifications: **", params$addSpec)))
}
```

```{r}
if(!is.null(nrow(params$rawData))){
  cat("**Raw data**")
}
```

```{r}
if(!is.null(nrow(params$rawData))){
  cat("\n")
  cat(paste("Spiked Concentration (Units): ", params$unit))
}
```

```{r}
if(!is.null(nrow(params$rawData))){
  knitr::kable(params$rawData)
}
```

```{r, fig.align='center', fig.width=15, fig.width=10, fig.align='center', dpi=300}
if(params$evalStd == T){
  params$stdPlot
}
```

```{r, fig.align='center', fig.width=15, fig.width=10, fig.align='center', dpi=300}
if(params$evalInv == T){
  params$invPlot
}
```

```{r}
if(params$weight != "" | params$order != ""| params$confb2 != "" | params$equation){
  cat("**Least squares regression parameters**")
  cat("\n\n")
  cat("The regression is performed using the spiked concentrations as the dependent variable (y) and the measurements as the independent variable (x).")
}
```

```{r}
if(params$weight != ""){
  if(params$weight == 1){
    cat("Weight: 1 (no weight)")
  }else if(params$weight == 2){
    cat(paste("Weight: ","1/x"))
  }else if(params$weight == 3){
    cat(paste("Weight: ","1/$x^2$"))
  }else{
    cat(paste("Weight:", "1/variance"))
  }
}
```

```{r}
if(params$confb2 != ""){
  
  cat(paste("Confidence interval on $b_2$ (quadratic term): ", params$confb2))
}
```

```{r}
if(params$order != ""){
  if(params$order == 1){
    cat("Order: Linear")
  }else{
    cat("Order: Quadratic")
  }
}
```

```{r}
if(params$equation){
  if(params$b2 != ""){
    tmp = pretty_print_eq(2, round(params$b0, 3), round(params$b1, 3), round(params$b2, 3))
    #tmp = paste(params$b2,"$x^2$ + ", params$b1, "$x$ + ", params$b0)
    cat(paste("Equation of the regression: ", tmp))
  }else{
    tmp = pretty_print_eq(1, round(params$b0, 3), round(params$b1, 3), round(0, 3))
    #tmp = paste(params$b1, "$x$ + ", params$b0)
    cat(paste("Equation of the regression: ", tmp))
  }
}
```

```{r}
if(params$ucrm != "" | params$ub0 != "" | params$uc != ""){
  cat("**Parameters used for measurement uncertainty calculation**")
}
```

```{r}
if(params$ucrm != ""){
  cat(paste("$u_{CRM}$ = ", params$ucrm))
}
```

```{r}
if(params$ub0 != ""){
  cat(paste("$u_{b0}$ = ", params$ub0))
}
```

```{r}
if(params$uc != ""){
  cat(paste("$u_{c}$ (combined standard uncertainty) = ", params$uc))
}
```

**Calculated Unknown Concentration**

```{r}
if(params$expUnc != ""){
  cat(paste(">",params$concentration, "±",  params$expUnc, params$unit))
}else{
  cat(paste(">",params$concentration, params$unit))
}
```

```{r}
if(params$confLim == T){
  cat(paste(">","The confidence interval for the unknown's concentration thus spans from",  params$conLow, "to",  params$conUpp, params$unit))
}
```

```{r}
if(params$confLev != ""){
  cat(paste(">","The expanded measurement uncertainty and confidence interval were calculated at",  params$confLev," confidence level"))
}
```

Report generated by EZMSA 1.0 (<https://toxbrigitte.shinyapps.io/EZMSA/>).
